Regridding user supplied mask
caracal-pipeline/caracal pull request #1314
Opened 2021-02-11 16:23 UTC by molnard89

This addition regrids the user supplied mask if it's different to the cube being made by the line worker. If the output cube is outside the supplied mask, caracal stops with an error (since montage doesn't do anything in this case). If it's only partially outside, the rest of the mask volume is filled up with 0s. Reprojection creates a float array with values between 0 and 1. These are rounded to the nearest integer (i.e. <0.5 becomes 0 while >0.5 goes to 1).

Requires montagepy, which is now added to the setup.py as a new requirement.

2021-02-11 16:41 UTC, paoloserra commented
Hey @molnard89 , after Marc's email yesterday I realised that it might be better to convert the input mask to 0's and 1's before running montage on it. If we do not, in a mask where the value of the detected pixels is the object ID (as in SoFiA's output masks) the interpolation may  give different results depending on whether an object has, e.g., ID = 1 or ID = 100. What  do you think?

2021-02-11 16:42 UTC, paoloserra commented
(Also, you  need to update with the  base branch.)

2021-02-11 16:53 UTC, paoloserra commented
Note  that installation with python 3.8 is failing because of the montagepy dependency :(

2021-02-11 17:00 UTC, molnard89 commented
@paoloserra just checked the code and I was lying in my description. It rounds to the nearest integer and that's it. Does WSCLEAN care about the actual value? In other words, are groups of pixels somehow cleaned together and if i.e. all pixels with value 12 (some ID) get a few 11s or 13s mixed in things go south during he clean? Or is it just mask = anything that's not a 0? I suspect it's the latter, in which case I think we're okay.

(you're right about the update with the base branch. I tried on escondida1, but it seems I failed :) )

2021-02-11 17:07 UTC, paoloserra commented
WSclean does not care: 0's = non-detected, anything else = detected. So rounding to the nearest integer is the same as cutting at 0.5. However, I think that the result of the regridding will depend on whether you've got, e.g., a bunch of pixels with value = 1 surrounded by 0's (the non-detected pixels) or a bunch of pixels with value = 100 surrounded by 0's. Think about the edge pixels of an object. I worry that we end up artificially enlarging the mask of an object with ID >> 1. E.g., if a pixel in the regridded mask is only 10% touched by a pixel belonging to the object, it gets value 0.1 if the object ID is 1, and 10 if the object ID is 100. In the former case the pixel is not detected in the regridded mask, in the latter it is detected.

2021-02-11 17:17 UTC, molnard89 commented
@paoloserra ah yes you are right. Okay, it's easy to do, I'll add it to the code tomorrow the latest.

2021-02-16 14:22 UTC, paoloserra commented
@molnard89 the code seems good to me, but  note that this is still failing with python 3.8. See https://github.com/caracal-pipeline/caracal/pull/1314/checks?check_run_id=1888886497#step:4:95 .

I do not know why. On my Mac I run python 3.8 and could pip-install montagepy alright. Any ideas?

2021-02-16 14:31 UTC, molnard89 commented
@paoloserra I've no idea what's wrong. :( I just created a python 3.8 conda environment locally and it also installed montagepy without a problem, and it worked on escondida1/ilifu too.

2021-02-16 14:33 UTC, paoloserra commented
time to summon the pro's... @SpheMakh @bennahugo @o-smirnov ?!?

2021-02-18 22:35 UTC, paoloserra requested changes
The `[0]` in the line https://github.com/caracal-pipeline/caracal/blob/4cf1400836f24e00b3257eae1fc5cf8463906eaf/caracal/workers/line_worker.py#L878 seems to be a mistake. It makes the fraction of 0's to go from 99.99% to ~50% in a simple test I've made. I think it should go.

2021-02-18 23:04 UTC, molnard89 commented
>The final [0] in the line

Ah, that might be a bug cause we have 3D arrays. I'll take a look tomorrow! Also to speed it up a bit it should change >1 pixels, not >0.

2021-03-09 14:08 UTC, paoloserra approved these changes

2021-06-15 09:14 UTC, gigjozsa commented
@molnard89 Apparently the build of MontagePy fails under Python 3.8. Can you check this?

2021-10-27 12:54 UTC, paoloserra submitted a review, later dismissed

2021-11-20 09:31 UTC, SpheMakh commented
retest this please

2021-11-20 10:43 UTC, SpheMakh commented
I don't have access to the jenkins server anymore. @o-smirnov , @Athanaseus , or @bennahugo check on this failure could you please check on this error

2021-11-22 09:03 UTC, Athanaseus commented
```2021-11-20 10:36:41 CARACal.Stimela.listobs-ms0 INFO: job started at 2021-11-20 10:36:41.692410
# 2021-11-20 10:36:43: Initial memory state:
# 2021-11-20 10:36:43:               total        used        free      shared  buff/cache   available
# 2021-11-20 10:36:43: Mem:          172Gi        20Gi        72Gi       107Mi        79Gi       150Gi
# 2021-11-20 10:36:43: Swap:         4.5Gi       388Mi       4.1Gi
# casa not found in /casa/casa-release-5.8.0-109.el7/lib/casa/bin
# Running CASA task 'listobs'
# Traceback (most recent call last):
#   File "/stimela_mount/code/run.py", line 8, in <module>
#     task.run()
#   File "/usr/local/lib/python3.8/dist-packages/Crasa/Crasa.py", line 107, in run
#     subprocess.check_call([self.casa, "--nogui", "--agg",
#   File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
#     raise CalledProcessError(retcode, cmd)
# subprocess.CalledProcessError: Command '['casa', '--nogui', '--agg', '--nocrashreport', '--log2term', '--logfile', '/stimela_mount/output/tmp/tmps_59n71t', '-c', '/stimela_mount/output/tmp/tmpb80tt0yd.py']' returned non-zero exit status 1.
2021-11-20 10:36:43 CARACal.Stimela.listobs-ms0 ERROR: cd /var/lib/jenkins/jobs/PR_meerkathi/workspace/366/test-output/51093b0/minitestConfig-singularity/.stimela_workdir-16374046015764134 && singularity returns error code 1
2021-11-20 10:36:43 CARACal.Stimela.listobs-ms0 ERROR: job failed at 2021-11-20 10:36:43.243713 after 0:00:01.551303
2021-11-20 10:36:43 CARACal ERROR: Job 'listobs-ms0:: Get observation information ms=1532022061_subset.ms' failed: cd /var/lib/jenkins/jobs/PR_meerkathi/workspace/366/test-output/51093b0/minitestConfig-singularity/.stimela_workdir-16374046015764134 && singularity returns error code 1 [PipelineException]
2021-11-20 10:36:43 CARACal INFO:   More information can be found in the logfile at output/logs-20211120-103640/log-caracal.txt
2021-11-20 10:36:43 CARACal INFO: exiting with error code 1```

2021-11-22 09:05 UTC, paoloserra commented
thanks @Athanaseus

Is the error the same in all other PRs?

2021-11-22 09:07 UTC, Athanaseus commented
> Is the error the same in all other PRs?

Yes, it is the same.

2021-11-22 09:14 UTC, SpheMakh commented
@Athanaseus could you post what is going in CASA itself.

2021-11-22 09:15 UTC, SpheMakh commented
NVM, I see that the `casa` binary was not found 

```
casa not found in /casa/casa-release-5.8.0-109.el7/lib/casa/bin
```

2021-11-22 09:41 UTC, SpheMakh commented
@Athanaseus could you please paste the docker command that was run for listobs

2021-11-22 09:42 UTC, SpheMakh commented
I can't reproduce this error, both with master and this branch.

2021-11-22 09:45 UTC, Athanaseus commented
```
Preparing singularity test (using minitestConfig.yml) in
/var/lib/jenkins/jobs/PR_meerkathi/workspace/366/test-output/51093b0/minitestConfig-singularity
Running singularity test (using minitestConfig.yml)
caracal -c minitestConfig.yml -ct singularity
2021-11-20 10:36:38 CARACal INFO: Invoked as /var/lib/jenkins/jobs/PR_meerkathi/workspace/366/test-output/51093b0/caracal_venv/bin/caracal -c minitestConfig.yml -ct singularity
2021-11-20 10:36:40 CARACal WARNING: Config file minitestConfig.yml schema version is 1.0.3, current CARACal version is 1.0.4
2021-11-20 10:36:40 CARACal WARNING: Will try to proceed anyway, but please be advised that configuration options may have changed.
2021-11-20 10:36:40 CARACal INFO: Loading pipeline configuration from minitestConfig.yml
2021-11-20 10:36:40 CARACal INFO: Version 1.0.4 installed at /var/lib/jenkins/jobs/PR_meerkathi/workspace/366/test-output/51093b0/caracal_venv/lib/python3.6/site-packages/caracal
2021-11-20 10:36:40 CARACal INFO: 
2021-11-20 10:36:40 CARACal INFO:   general:
2021-11-20 10:36:40 CARACal INFO:     title:                        ""
2021-11-20 10:36:40 CARACal INFO:     msdir:                        msdir
2021-11-20 10:36:40 CARACal INFO:     rawdatadir:                   /var/lib/jenkins/jobs/PR_meerkathi/workspace/366/test-output/pull_request_data/
2021-11-20 10:36:40 CARACal INFO:     input:                        input
2021-11-20 10:36:40 CARACal INFO:     output:                       output
2021-11-20 10:36:40 CARACal INFO:     prefix:                       mypipelinerun
2021-11-20 10:36:40 CARACal INFO:     prep_workspace:               True
2021-11-20 10:36:40 CARACal INFO:     init_notebooks:               std-progress-report, project-logs
2021-11-20 10:36:40 CARACal INFO:     report_notebooks:             [detailed-final-report]
2021-11-20 10:36:40 CARACal INFO:     final_report:                 False
2021-11-20 10:36:40 CARACal INFO: 
2021-11-20 10:36:40 CARACal INFO:   getdata:
2021-11-20 10:36:40 CARACal INFO:     dataid:                       [1532022061_subset]
2021-11-20 10:36:40 CARACal INFO:     extension:                    ms
2021-11-20 10:36:40 CARACal INFO:     report:                       False
2021-11-20 10:36:40 CARACal INFO:     ignore_missing:               False
2021-11-20 10:36:40 CARACal INFO: 
2021-11-20 10:36:40 CARACal INFO:   obsconf:
2021-11-20 10:36:40 CARACal INFO:     target:                       [all]
2021-11-20 10:36:40 CARACal INFO:     gcal:                         [all]
2021-11-20 10:36:40 CARACal INFO:     bpcal:                        [longest]
2021-11-20 10:36:40 CARACal INFO:     fcal:                         [longest]
2021-11-20 10:36:40 CARACal INFO:     xcal:                         [longest]
2021-11-20 10:36:40 CARACal INFO:     refant:                       0
2021-11-20 10:36:40 CARACal INFO:     maxdist:                      1000.0
2021-11-20 10:36:40 CARACal INFO:     minbase:                      150.0
2021-11-20 10:36:40 CARACal INFO:     report:                       False
2021-11-20 10:36:40 CARACal INFO:     obsinfo:
2021-11-20 10:36:40 CARACal INFO:       enable:                       True
2021-11-20 10:36:40 CARACal INFO:       listobs:                      True
2021-11-20 10:36:40 CARACal INFO:       summary_json:                 True
2021-11-20 10:36:40 CARACal INFO:       vampirisms:                   False
2021-11-20 10:36:40 CARACal INFO:       plotelev:
2021-11-20 10:36:40 CARACal INFO:         enable:                       True
2021-11-20 10:36:40 CARACal INFO:         plotter:                      owlcat
2021-11-20 10:36:40 CARACal INFO: 
2021-11-20 10:36:40 CARACal INFO:   transform:
2021-11-20 10:36:40 CARACal INFO:     enable:                       True
2021-11-20 10:36:40 CARACal INFO:     field:                        calibrators
2021-11-20 10:36:40 CARACal INFO:     label_in:                     ""
2021-11-20 10:36:40 CARACal INFO:     label_out:                    cal
2021-11-20 10:36:40 CARACal INFO:     report:                       False
2021-11-20 10:36:40 CARACal INFO:     split_field:
2021-11-20 10:36:40 CARACal INFO:       enable:                       True
2021-11-20 10:36:40 CARACal INFO:       time_avg:                     ""
2021-11-20 10:36:40 CARACal INFO:       chan_avg:                     1
2021-11-20 10:36:40 CARACal INFO:       col:                          data
2021-11-20 10:36:40 CARACal INFO:       correlation:                  ""
2021-11-20 10:36:40 CARACal INFO:       scan:                         ""
2021-11-20 10:36:40 CARACal INFO:       create_specweights:           True
2021-11-20 10:36:40 CARACal INFO:       spw:                          ""
2021-11-20 10:36:40 CARACal INFO:       nthreads:                     1
2021-11-20 10:36:40 CARACal INFO:     obsinfo:
2021-11-20 10:36:40 CARACal INFO:       enable:                       True
2021-11-20 10:36:40 CARACal INFO:       listobs:                      True
2021-11-20 10:36:40 CARACal INFO:       summary_json:                 True
2021-11-20 10:36:40 CARACal INFO: 
2021-11-20 10:36:40 CARACal INFO:   prep:
2021-11-20 10:36:40 CARACal INFO:     enable:                       True
2021-11-20 10:36:40 CARACal INFO:     label_in:                     cal
2021-11-20 10:36:40 CARACal INFO:     field:                        calibrators
2021-11-20 10:36:40 CARACal INFO:     tol:                          360.0
2021-11-20 10:36:40 CARACal INFO:     tol_diff:                     1.0
2021-11-20 10:36:40 CARACal INFO:     clearcal:                     False
2021-11-20 10:36:40 CARACal INFO:     report:                       False
2021-11-20 10:36:40 CARACal INFO:     manage_flags:
2021-11-20 10:36:40 CARACal INFO:       enable:                       True
2021-11-20 10:36:40 CARACal INFO:       mode:                         legacy
2021-11-20 10:36:40 CARACal INFO:       version:                      auto
2021-11-20 10:36:40 CARACal INFO: 
2021-11-20 10:36:40 CARACal INFO:   flag:
2021-11-20 10:36:40 CARACal INFO:     enable:                       True
2021-11-20 10:36:40 CARACal INFO:     field:                        calibrators
2021-11-20 10:36:40 CARACal INFO:     label_in:                     cal
2021-11-20 10:36:40 CARACal INFO:     calfields:                    auto
2021-11-20 10:36:40 CARACal INFO:     overwrite_flagvers:           False
2021-11-20 10:36:40 CARACal INFO:     report:                       True
2021-11-20 10:36:40 CARACal INFO:     rewind_flags:
2021-11-20 10:36:40 CARACal INFO:       enable:                       True
2021-11-20 10:36:40 CARACal INFO:       mode:                         reset_worker
2021-11-20 10:36:40 CARACal INFO:       version:                      auto
2021-11-20 10:36:40 CARACal INFO:     flag_autocorr:
2021-11-20 10:36:40 CARACal INFO:       enable:                       True
2021-11-20 10:36:40 CARACal INFO:     flag_shadow:
2021-11-20 10:36:40 CARACal INFO:       enable:                       True
2021-11-20 10:36:40 CARACal INFO:       tol:                          0.0
2021-11-20 10:36:40 CARACal INFO:       full_mk64:                    False
2021-11-20 10:36:40 CARACal INFO:     flag_rfi:
2021-11-20 10:36:40 CARACal INFO:       enable:                       True
2021-11-20 10:36:40 CARACal INFO:       flagger:                      aoflagger
2021-11-20 10:36:40 CARACal INFO:       col:                          DATA
2021-11-20 10:36:40 CARACal INFO:       aoflagger:
2021-11-20 10:36:40 CARACal INFO:         strategy:                     firstpass_Q.rfis
2021-11-20 10:36:40 CARACal INFO:         ensure_valid:                 True
2021-11-20 10:36:40 CARACal INFO:         readmode:                     auto
2021-11-20 10:36:40 CARACal INFO:       tricolour:
2021-11-20 10:36:40 CARACal INFO:         backend:                      numpy
2021-11-20 10:36:40 CARACal INFO:         mode:                         auto
2021-11-20 10:36:40 CARACal INFO:         strategy:                     mk_rfi_flagging_calibrator_fi [...]

2021-11-22 10:00 UTC, paoloserra commented
Any chance this is related to the new backend option?

2021-11-22 10:07 UTC, SpheMakh commented
> Any chance this is related to the new backend option? 

I think singularity made a mistake when making the casa image. It works on my machine with docker and singularity (version 3.9.0-rc.1)

2021-11-22 15:09 UTC, SpheMakh commented
retest this please

2021-11-22 17:21 UTC, SpheMakh commented
retest this please

2021-11-23 12:39 UTC, SpheMakh commented
retest this please

2021-11-23 12:49 UTC, SpheMakh commented
retest this please

2021-11-23 15:39 UTC, SpheMakh approved these changes

2021-11-23 15:39 UTC, merged