Get flag summary from latest msutils-1.2.0 with plots
caracal-pipeline/caracal pull request #1328
Opened 2021-05-10 14:58 UTC by Athanaseus

- Flags stats from `msutils`
- Remove bokeh
- resolves #1292

2021-05-28 10:09 UTC, o-smirnov commented
ok to test

2021-05-28 10:11 UTC, o-smirnov approved these changes
LGTM. I assume you've checked that the plots are generated as before?

2021-05-28 10:12 UTC, Athanaseus commented
yes, I tested that.

2021-06-15 09:08 UTC, o-smirnov requested changes

2021-06-15 09:08 UTC, o-smirnov commented on caracal/workers/selfcal_worker.py
>                                             'slefcal-summary-{2:d}.json').format(
selfcal-summary? @Athanaseus

2021-06-15 09:08 UTC, o-smirnov commented on caracal/workers/selfcal_worker.py
>                                             'slefcal-summary-{2:d}.json').format(
@Athanaseus could you please fix the typo in the filename.

2021-06-18 09:57 UTC, o-smirnov approved these changes

2021-06-18 09:57 UTC, merged